### ISSUE TITLE
Action to push/publish the results of the apko-build action?

### ISSUE THREAD

**Issue by kastl-ars** [chainguard-dev/actions#440]
I found the [apko-build action](https://github.com/chainguard-dev/actions/tree/main/apko-build) and was wondering, if there was a complimentary action to publish/push the image to e.g. the Github registry? As far as I understood the result of the apko-build action is only a local file?

Kind Regards,
Johannes

**Comment by kastl-ars** [comment]
OK, now I found [github.com/chainguard-images/actions/tree/main/apko-publish](https://github.com/chainguard-images/actions/tree/main/apko-publish) and am confused...

**Comment by imjasonh** [comment]
First of all, your confusion is warranted. We haven't done a great job of maintaining clear documentation for these actions. Part of the reason is that we don't use these actions ourselves, so they tend to bitrot when underlying tools change. I would not recommend using any of these actions, personally. Instead, just install `apko` in your CI pipeline, and run `apko build`/`apko publish` directly. The actions don't provide much value beyond that to be honest.

With that said, apko-build [does publish](https://github.com/chainguard-dev/actions/blob/main/apko-build/action.yaml#L83), but it's also [deprecated](https://github.com/chainguard-dev/actions/blob/main/apko-build/action.yaml#L77), in favor of [chainguard-images/actions/apko-publish](https://github.com/chainguard-images/actions/blob/main/apko-publish/action.yaml), which I also wouldn't recommend. Like I said, none of this is very clear. Sorry about that 😞

**Comment by kastl-ars** [comment]
Thanks for the reply @imjasonh 
I used the distroless/actions (aka [chainguard-images/actions/apko-publish](https://github.com/chainguard-images/actions/blob/main/apko-publish/action.yaml)) and it worked flawlessly, so for the moment I am happy.

Why are you not recommending them? Building and publishing an action and then not recommending them seems kind of strange :-)

Anyway, closing this as the actual question was answered.

Kind Regards,
Johannes
